### ISSUE TITLE
Pressing numeric keys when all flashcards reviewed

### ISSUE THREAD

**Issue by NuDogma** [mnemosyne-proj/mnemosyne#100]
When all the flashcards have been reviewed and I press the numeric keys 1,2,3,4,5 and 0 a window pops up with the following message using the latest version (2.6.1):
![screenshot 35](https://user-images.githubusercontent.com/36926154/48438833-28719880-e785-11e8-82b3-b4a775149bd8.png)

**Comment by pbienst** [comment]
Fixed in the development version, thanks for the report!
