### ISSUE TITLE
Decision to use SM2

### ISSUE THREAD

**Issue by BryanJBryce** [mnemosyne-proj/mnemosyne#101]
Is there a reason why the SM2 algorithm is used when later versions, e.i. SM5, SM11 exist?

**Comment by BryanJBryce** [comment]
Hmm...reading here: https://www.supermemo.com/english/ol/sm5.htm#evaluation and here it looks like  the algorithm gets progressively more complicated after SM2 and that the improvement the algorithms bring may not be significant enough to consider implementing them. I really like the simplicity of the SM2 algorithm. Subsequent algorithms seem like the author is trying to do what we'd do now with AI but by hand.

**Comment by BryanJBryce** [comment]
This review is an interesting evaluation as well: https://nihongoperapera.com/mnemosyne-one-year.html

**Comment by pbienst** [comment]
Agreed :-)

Peter


________________________________
