### ISSUE TITLE
Directory listing in window after sync

### ISSUE THREAD

**Issue by janha** [mnemosyne-proj/mnemosyne#104]
A somewhat strange bug I stumbled onto. I had done my reviews on the mobile app and when I synced back with the desktop version it showed a listing of my root directory in the question window. I clicked on the directory names, and am taken to the directory I clicked. 

![screenshot from 2019-01-06 20-30-36](https://user-images.githubusercontent.com/7120323/50740700-a5077d00-11f2-11e9-9829-04f49e8601ba.png)

I activated a new category, and was taken to the first  question due on that category. Everything seems normal and in working condition.

**Comment by pbienst** [comment]
Very strange bug indeed. Can you reproduce this?

**Comment by pbienst** [comment]
Closing due to lack of feedback.
