### ISSUE TITLE
An Unexpected Error Has Occurred.

### ISSUE THREAD

**Issue by RingOfProgrammers** [mnemosyne-proj/mnemosyne#109]
I'm not sure if this is the right place to write this, but I received the following error message:

> An unexpected error has occurred.
>Please forward the following info to the developers:
>
>Traceback (innermost last):
>  File "mnemosyne\pyqt_ui\review_wdgt.pyo", line 328, in grade_answer
>  File "mnemosyne\libmnemosyne\review_controllers\SM2_controller.pyo", line 159, in grade_answer
>  File "mnemosyne\libmnemosyne\schedulers\SM2_mnemosyne.pyo", line 556, in grade_answer
>  File "mnemosyne\libmnemosyne\loggers\database_logger.pyo", line 107, in log_repetition
>  File "mnemosyne\libmnemosyne\databases\_sqlite3.pyo", line 72, in execute
> DatabaseError: database disk image is malformed

I had just added 26 new front-to-back and back-to-front cards for learning Morse Code.  The front of each card had an audio file with an `src` pointing to an absolute file location.  I went through several cards before the error came up when I think I graded it a 4.

Sorry if this is the wrong place to enter such an error.  If there is another place I should post this (or if this issue already exists), please let me know.

**Comment by pbienst** [comment]
I'm afraid this error indicates corruption with your database, which could be caused by e.g. a failing drive.

I would suggest to get your data off this drive as soon as possible and revert to a previous backup:
https://mnemosyne-proj.org/help/backups.php
