### ISSUE TITLE
Question on Decision for Easiness Factor Calculation

### ISSUE THREAD

**Issue by moebaca** [mnemosyne-proj/mnemosyne#112]
Hey Mnemosyne devs. I was wondering if you could enlighten me on your programmatic choice for determining ease. In the SM2 spec (https://www.supermemo.com/english/ol/sm2.htm) the formula to calculate easiness factor is:

EF+(0.1-(5-q)*(0.08+(5-q)*0.02))

However, in Mnemosyne, you've hard coded the ease calculation from grade 2-5 => 2-5 by statically applying -= 0.16, -= 0.14, += 0, and 0.10 respectively.

The -0.14, +0 and 0.10 hold true if the previous ease was 2.5 (the -0.16 should actually be -0.32), but start to vary wildly when you change the previous easiness factor.

I just wanted to know what the reasoning was behind adjusting the easiness factor by a static amount as opposed to Wozniak's dynamic formula?

Thanks in advance!

**Comment by pbienst** [comment]
This code was actually written more than 10 years ago, so the details are vague. I probably even copied the algorithm from Mnemosyne's predecessor, FullRecall.

Anyway, apart from the -.32, is the formula really that different? Also on the SM webpage, the increments to EF only depend on q (the grade). (it says EF' = EF + f(q), not EF' += EF + f(q))

**Comment by moebaca** [comment]
Thank you for responding pbienst. I just wanted to let you know your code is infinitely better written than Ankis which I believe were created around the same timeframe. That's not a subjective comment either.. go take a look at their scheduler compared to Mnemosyne's and you'll see what I mean. That is why I asked here instead of there because I spent 10 hours (not even exaggerating) trying to decipher their cryptic spaghetti and coming to Mnemosyne is just so much easier on the eyes.

But back to the question. The formula states EF is the old easiness factor and 'EF is the calculated one as a result of the old EF bring added to the rest of the code.

So if you get a calculated EF of 2.4 for example, then the next round you go to calculate the next EF based off of that 2.4 the formula spits out different numbers no matter the quality.

It's all good though. I honestly don't know how much it matters in the long run these minor details of how everyone is implementing SM2. The difference is a few days here and there I believe so it's almost like an additional layer of noise once you get to the higher intervals.

Thanks for your time.

**Comment by pbienst** [comment]
Thanks for the compliment, I like clean code! 

From the sm2 site:

EF':=EF+(0.1-(5-q)*(0.08+(5-q)*0.02))
where:
EF' - new value of the E-Factor,
EF - old value of the E-Factor,
q - quality of the response in the 0-5 grade scale.

So, the difference between EF' and EF only depends on q, right?
