### ISSUE TITLE
Random black bar in card.

### ISSUE THREAD

**Issue by Elderry** [mnemosyne-proj/mnemosyne#113]
In version 2.6.1, there will randomly appear some black bars in my cards, like this:
![image](https://user-images.githubusercontent.com/1892221/54443981-c8175580-477c-11e9-916c-88b861998ccd.png)
The location and size of the bar is also random. I'm almost sure this bug is introduced in 2.6.1 because I use mnemosyne every day, literally.
Here are some information that may help:
Mnemosyne Version: 2.6.1
OS: Windows 10 Pro Version 1809
Monitor Resolution: 4K (3840 * 2160)
Cards sometimes have image in it, format like:
![image](https://user-images.githubusercontent.com/1892221/54444650-301a6b80-477e-11e9-8424-85d665773275.png)

**Comment by pbienst** [comment]
I don't think this is a problem with Mnemosyne itself, but rather the GUI library it uses (Qt) and/or its interaction with your video drivers. I'm afraid the most I can do is recommending you update your graphics drivers, or try starting Mnemosyne with the --qt-opengl=desktop run time argument...
