### ISSUE TITLE
Database not Saving Automatically

### ISSUE THREAD

**Issue by RingOfProgrammers** [mnemosyne-proj/mnemosyne#115]
Mnemosyne is stuck on giving me the same cards at startup.  When I rate the first few cards, exit, and reopen Mnemosyne, none of the progress gets saved.  It found out that general settings saves and editing cards saves but not (de)activating cards or reviewing cards.  There is no error message or anything.

I just found out that pressing "File->Save" works, but I have to press "Save" each time before I exit, and it won't save automatically.  So it's not automatically saving when I exit Mnemosyne.  I've tried restarting my computer to no avail.  Is there some way I can fix this other than reinstalling Mnemosyne?

I recorded a video of my error but found that I can't post it in here, so I'll just explain what I did in the video.  The first time I opened Mnemsoyne, I did a few cards, exited, and reopened to the first card it gave me.  Then I did some cards, saved it via "File->Save", exited, and reopened with everything saved.  Finally, I did some cards, saved it (File->Save), and did a few more cards.  When I reopened it the third time, only the cards that I did before I pressed "Save" were saved.  Apparently Mnemosyne isn't automatically saving before I exit.

**Comment by pbienst** [comment]
Which version and os is this? Try upgrading to the latest version first.

**Comment by RingOfProgrammers** [comment]
I was running 1.3.6 on Windows 10, but the same problem still occurred after I updated just now to 1.6.1.

**Comment by pbienst** [comment]
You do mean 2.6.1 I hope? Is there some antivirus software interfering or is your Mnemosyne datafolder write-protected? 

You might try deleting the datafolder (but backing up its contents!) and then doing a file - import from your 1.3 database.

**Comment by RingOfProgrammers** [comment]
Yeah, sorry.  I meant 2.3.6 and 2.6.1.  I had the database stored in two places, one on my computer and one on a pendrive as a backup.  So I tried pressing "File->Save As" to save the "default.db" on my pendrive overwriting the old one I had and then deleting the one on my computer and replacing it with the new one on my pendrive.  However, that didn't fix the issue.  I also ran a Lock Finder program on the database and found that nothing was locking the file.

Mnemosyne had been working fine for quite a while in the past.  I don't know why any antivirus software would choose now to start interfering.  And I can save the database manually, it just doesn't save automatically.

I just opened Mnemosyne and then closed it without doing something, and the following error popped up, though I don't know if it's related to my problem:

"Traceback (innermost last):
  File "mnemosyne\pyqt_ui\mnemosyne", line 291, in <module>
  File "mnemosyne\libmnemosyne\__init__.py", line 380, in finalise
  File "mnemosyne\livmnemosyne\loggers\database_logger.py", line 56, in saved_database
  File "mnemosyne\libmnemosyne\database\SQLite_logging.py", line 72, in execute sqlite3.OperationalError: dist I/O error"

(You should really make the errors copy/pasteable 😉)

**Comment by pbienst** [comment]
There is something funny with your drive. To debug it, I would keep de usb drive completely out of the picture for the time being,  delete the entire mnemosyne datadir in c:/users/you/appdata/roaming and not just the database, and then try again.

**Comment by RingOfProgrammers** [comment]
I keep the default.bd_media folder, cards.cards, config.db, default.db, default.db-journal, and questionsAll.cards files in a separate folder than the AppData folder.  However, I deleted both the AppData folder and my own Mnemosyne Questions folder and started up Mnemosyne.  It worked perfectly normal.  Then I copied the Mnemosyne Questions folder from my pendrive back onto my computer and opened it with Mnemosyne.  When I tested it, the same problem continued.  So whatever is wrong must be with my one of the files.  I tried deleting the files one by one.  I deleted all but the card files so that it created a new database.  Everything worked fine except, of course, that all my questions were due today.  So the error seems to be with the database.db file.  What's wrong with it, I can't imagine since manually saving works.  Maybe mnemosyne saves things differently when you press "Save" than when you simply exit the app.  If so, the perhaps the database somehow rejects the later method of saving and accepts the first.

One more thing I'll try is to completely unistall Mnemosyne from my computer including the data I have in my own folder (keeping it saved on my pendrive) and see if that fixes it.

**Comment by pbienst** [comment]
Once you have a fresh database where things work, do a file - import of your old db file. That will insert your old cards in the new db.

**Comment by RingOfProgrammers** [comment]
Thanks, that seems to have worked, although I got the following error: 

![Mnemosyne Error](https://user-images.githubusercontent.com/34894078/54853336-fbe70380-4cc5-11e9-9979-73312aa24937.jpg)

Despite the error, it seems to be working.

**Comment by pbienst** [comment]
There was indeed something wrong with your old database, more concretely with the log of the old repetitions.
