### ISSUE TITLE
Add cards window doesn't work with iBus

### ISSUE THREAD

**Issue by HiddenWindshield** [mnemosyne-proj/mnemosyne#116]
The "Add cards" window doesn't accept text from iBus. (I haven't tried it with any other IMEs, so this may or may not also occur with them.) This makes it impossible to type text in many other languages.

Steps to reproduce:
1. Open the "Add cards" window.
2. Switch to Anthy in the iBus control center.
3. Type the text 「わたし」

Actual results:
The window completely ignores the IME, and displays the Roman equivalent "watashi".

Expected results:
The window should actually display the text 「わたし」.

Workaround:
Open a text editor, type the desired text into it, then copy and paste.

**Comment by pbienst** [comment]
This doesn't look like it's a Mnemosyne issue :

https://forum.manjaro.org/t/ibus-doesnt-work-in-some-but-not-all-qt-kde-applications/24265
