### ISSUE TITLE
Setting a different font in the android app

### ISSUE THREAD

**Issue by rrschmidt** [mnemosyne-proj/mnemosyne#130]
I tried using the "Sans Forgetica" (https://en.wikipedia.org/wiki/Sans_forgetica) font in the Mnemosyne android app through third party apps (iFont, Go Launcher) but had no success. 

Where is a good place to start if I want to add this feature directly into the android app? Is the render chain and the HtmlCss renderer ( in mnemosyne/mnemosyne/libmnemosyne/renderers/html_css.py 
 ) also used by android?

**Comment by pbienst** [comment]
The HtmlCss is indeed used by the Android client:

https://github.com/mnemosyne-proj/mnemosyne/blob/master/mnemosyne/android_python/android_render_chain.py

However, I think supporting custom fonts will primarily need to be implemented on the Java side.

Thanks for looking into this!

**Comment by pbienst** [comment]
Feel free to reopen this if you make progress on this issue.
