### ISSUE TITLE
use of depreceated command in server application

### ISSUE THREAD

**Issue by hal50000** [mnemosyne-proj/mnemosyne#131]
Hey everyone, 

since python 3.2 the use of cgi.parse is depreceated in python. 

in openSM2sync/server.py it is still in use leading to a crash under Arch linux using python3.8

importing urllib in this file and changing line 155:

args = cgi.parse_qs(environ["QUERY_STRING"])

to 

args = urllib.parse.parse_qs(environ["QUERY_STRING"])

resolves this problem and mnemosyne runs again like a charm.

Could someone please resolve this (sorry, new to github....)

Thank you very much and best regards,
 
Hal

**Comment by pbienst** [comment]
Committed, thanks for spotting this!
