### ISSUE TITLE
UTF8 encoding error when syncing Android to Windows

### ISSUE THREAD

**Issue by wwiecek** [mnemosyne-proj/mnemosyne#133]
Hope it's Ok to post this here.

![image](https://user-images.githubusercontent.com/20645798/71289893-3ae5da80-2366-11ea-97dc-0b0f461425da.png)
That is what I got when syncing my library between 2.1 Android version and 2.7 on PC. Can't push the remote version to PC due to the above. Never had this problem before & pushing cards from PC to Android was not a problem.

udcc3 seems to be [this](https://charbase.com/dcc3-unicode-invalid-character)
Is there a way to search for the problematic chars in the database? I don't know how much of it is in plaintext.

My cards are mix of English, Polish, Spanish, with some TeX too. My currently synced DB is 5,000+ cards and quite old.

**Comment by pbienst** [comment]
I'm working on upgrading the Python version for Android, although it is rather difficult.

Meanwhile, just manually copy the database to your pc, delete it on the phone, and sync again.

**Comment by wwiecek** [comment]
Thanks!

**Comment by wwiecek** [comment]
Hi again,
I got this on PC today:

![image](https://user-images.githubusercontent.com/20645798/71590609-1f768e80-2b21-11ea-902d-526dbbd78a17.png)

same DB as I described above. I have my DB on custom path within a Dropbox folder. I assume Dropbox was interfering but letting you know just in case it's something else.

**Comment by pbienst** [comment]
Yes, that is the risk of using Dropbox, I'm afraid...

**Comment by wwiecek** [comment]
Thanks! Was just letting you know in case something else was triggering that.

**Comment by vmulders** [comment]
Hi, I have the same MATPLOTLIBDATA message

**Comment by pbienst** [comment]
The matplotlib message is harmless, and will be fixed in the next release.

**Comment by pbienst** [comment]
Should be fixed with latest beta release from Google Play (you need to opt in for beta release on the Google Play store page of Mnemosyne to get it). It should move to the stable release channel in 1 or 2 weeks.
