### ISSUE TITLE
test suite instructions busted after 8688711bc788

### ISSUE THREAD

**Issue by crobinso** [mnemosyne-proj/mnemosyne#135]
I'm trying to run the test suite. But the output doesn't look right:

```console
...
make[1]: Leaving directory '/home/crobinso/src/mnemosyne/po'
python3 -m nose -v tests
test_configuration.TestConfiguration.test_default_language_default ... ok
test_configuration.TestConfiguration.test_supported_language_as_default ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.230s

OK
```

Turns out, `nose` doesn't run exectuable files by default, unless it is passed the `--exe` option. And the 8688711bc788 mega commit seems to have made all test files executable except one.

So it seems like either that executable bit should be changed, or the Makefile and docs need to be updated to include that --exe option

**Comment by pbienst** [comment]
Fixed, thanks for reporting this!
