### ISSUE TITLE
Issue with viewing PDFs inside Mnemosyne using anchor tag

### ISSUE THREAD

**Issue by NuDogma** [mnemosyne-proj/mnemosyne#145]
Hi. When I want to view a PDF as an answer inside Mnemosyne I write an anchor HTML tag &lt;a href="file://whatever.pdf"&gt;click here&lt;/a&gt;.

So far so good.

But when I want to go to a specific page of the PDF appending #page=[page number] to the end of the link's URL it doesn't work. It always opens on the first page.

I've tried this with an html file with the Chrome browser and it works.

**Comment by pbienst** [comment]
I'm not sure this is something Mnemosyne has an influence over. All of the html is handled by Qt's widget, so it's best that you direct this request there...
