### ISSUE TITLE
Consider moving generic PR/git/github tutorial to the bottom of readme or a separate file

### ISSUE THREAD

**Issue by matkoniecz** [mnemosyne-proj/mnemosyne#146]
Anyone (except completely newbies) should be capable of finding info how branches in git work (or be already aware of that).

This kind of info may be useful in readme, but maybe move it below repo-specific content?

I see that there are no open PR so  would be happy to make one (assuming that it will not be rejected).

**Comment by pbienst** [comment]
No problem moving that info to the bottom of the file.
