### ISSUE TITLE
debug file has no debug data

### ISSUE THREAD

**Issue by matkoniecz** [mnemosyne-proj/mnemosyne#147]
Typical session:

```
mnemosyne --debug=/home/mateusz/Desktop/why_mnemosyne_is_failing.txt
Attribute Qt::AA_ShareOpenGLContexts must be set before QCoreApplication is created.
Icon theme "elementary" not found.
nouveau: kernel rejected pushbuf: No such file or directory
nouveau: ch10: krec 0 pushes 0 bufs 2 relocs 0
nouveau: ch10: buf 00000000 00000002 00000004 00000004 00000000
nouveau: ch10: buf 00000001 00000006 00000004 00000000 00000004
python3: ../nouveau/pushbuf.c:723: nouveau_pushbuf_data: Assertion `kref' failed.
Aborted (core dumped)
```

debug file that I specified is created but empty and is not containing even what I see in stdout.

Lubuntu 19.10 - Mnemosyne build from source is crashing/freezing all the time (but it is not what I reporting as I am unable to track the root cause for now).

I upgraded OS, sadly for Ubuntu 19.10 Mnemosyne version in packages is completely broken (at least for me) (also problem but not what I report as AFAIK packages are maintained by other people).

Sadly, I no longer have a nice crashes during compilations (like #73) but instead Mnemosyne is freezing/crashing - sometimes on the startup, sometimes on answering, on maximalising the window.

**Comment by pbienst** [comment]
This is expected : this was a temporary mechanism to log specific events, not to give a whole lot of verbose info that is also printed to the terminal.

**Comment by matkoniecz** [comment]
In general I would be happy to see more debug info about what is going wrong. For now I think that I did all obvious things like

- upgrading OS
- compiling from latest source
- running version with all debug options enabled

**Comment by matkoniecz** [comment]
> this was a temporary mechanism to log specific events

What is the current mechanism to get more info what is going wrong?

**Comment by pbienst** [comment]
The Open source Nvidia drivers are known to cause some issues under Linux. I guess this is what's going on.

**Comment by matkoniecz** [comment]
Note that proprietary Nvidia drivers also are likely to cause issues, in my case system failed to boot (removal of nvidia driver package using recovery mode fixed the issue).

I would recommend checking your backups before doing this.
