### ISSUE TITLE
Mnemosyne 2.4.0.1 crash on Linux Cinnamon 19.1

### ISSUE THREAD

**Issue by bugatt1** [mnemosyne-proj/mnemosyne#151]
When I open the menu "Cards-Browser" I receive the following error message:
>>An unexpected error has occurred.
Please forward the following info to the developers:
Traceback(innermost last):
File "usr/lib/python3/dist-packages)mnemosyne/pyqt_ui/browse_cards_dlg.py" line 263, in paint style.subElementRect (Qtwidgets.QStyle.SE_ItemViewText, option)
TypeError: subElementRect (Qtwidgets.QStyle.SE_ItemViewText, option): not enough arguments<<
Do anybody have an idea what to do? Tks-bugatt1

**Comment by pbienst** [comment]
Make sure you are using the latest version. 
Does this also happen on an empty database?
Also, try to upgrade the PyQt5 library.

**Comment by bugatt1** [comment]
Thanks for responding. I took the latest version from Ubuntu/Linux Mint software center which is 2.4.0.1. And yes, that happens also with an empty database. Could you give me a hint how to update PyQt5 lib?

**Comment by pbienst** [comment]
I meant the latest version from the Mnemosyne website. 2.4 is really ancient, we are at 2.7 now...
