### ISSUE TITLE
Download links in download page is outdated.

### ISSUE THREAD

**Issue by Elderry** [mnemosyne-proj/mnemosyne#154]
In [download page](https://mnemosyne-proj.org/download-mnemosyne.php), some download links are outdated.
For Windows version, it is `https://sourceforge.net/projects/mnemosyne-proj/files/mnemosyne/mnemosyne-2.7/mnemosyne-2.7-setup.exe/download`, but `*2.7.1*` is expected. As well as the macOS version.

**Comment by pbienst** [comment]
Fixed the link for the Windows version, thanks!

Note that OSX is still on 2.7, as mentioned on that page.
