### ISSUE TITLE
Problem with Activating Cards

### ISSUE THREAD

**Issue by emilnetzer** [mnemosyne-proj/mnemosyne#157]
I am reporting a possible bug in Mnemosyne 2.7.1. I wish to make active  20 cards with the tag “15 Pronouns en”. I select these cards by clicking Study located on the bar at the top of the window. The result is as follows:  Scheduled: 3112  Not memorized: 850 Active: 10363
I expected to the number of active cards to be 20. The total number of cards is 10383. The cards made active is 10363 and appear to be the total number of cards less cards with tag “15 Pronouns  en”. This problem occurs with other tags”

**Comment by pbienst** [comment]
In 'activate cards' are you sure the drop down box says 'having any of these tags' and not 'not having any of these tags'?

**Comment by emilnetzer** [comment]
I select "Study" which produces a pull-down menu. I select "(De)activate …" from the pull down menu.

As far as I know, there is no option in Mnemosyne to activate cards "not having these tags".

**Comment by pbienst** [comment]
Look in the dialog you get when choosing (De)activate cards, the option is in there. You probably changed it by accident from its default value.

**Comment by emilnetzer** [comment]
After I click "Study", a dialog box opens with four options. The option checked is Scheduled -> forgotten -> new. This is the option I use every time I activate cards, including activations that work correctly.  I cannot see any other dialog boxes or messages.

**Comment by emilnetzer** [comment]
I found the cause of the problem. As you suggested, there is an option to activate all cards except except those chosen. I must have chosen this option by accident. Please close this issue. Thanks very much for your help.
