### ISSUE TITLE
Better Documentation on libmnemosyne

### ISSUE THREAD

**Issue by alxiong** [mnemosyne-proj/mnemosyne#159]
Thanks for open-sourcing such an aweseome tool! 👍 

Improvement of documentation of the internal workings of `libmnemosyne` would be greatly appreciated. (or visualized architecture/diagram would be even better)

While the Overview section `libmnemosyne/doc/` is somewhat illuminating for the data model and rendering process. I'm quite uncertain the interplay of `ActivityCriterion` and `Scheduler` and `review_controller`. 

❓ Specifically, my question is 
- striping off the Post-scheduled chained-rendering, what are the list of data a Card carry that the scheduler need? 
- And how does the `criteria` componennt and `review_controller` pull cards out of the pool and feed to the scheduler?

Could you please help me clarify that, or maybe you have any docs that explain the mechanism? 😃

**Comment by pbienst** [comment]
The rendering is completely irrelevant for the scheduler. The main Card variables which play a role are:
```
        self.grade = -1
        self.next_rep = -1
        self.last_rep = -1
        self.easiness = 2.5
        self.acq_reps = 0
        self.ret_reps = 0
        self.lapses = 0
        self.acq_reps_since_lapse = 0
        self.ret_reps_since_lapse = 0
```
The Criterion component does not interact directly with the Scheduler. Rather, it sets a card.active value to True or False, and the Scheduler only pulls out active cards.

The ReviewController is a bit of a higher level component than the Scheduler, and deals with things like updating the UI if you review.

Hope this clarifies things, but don't hesitate to ask follow-up questions if required.

Out of curiosity, what are you building?

**Comment by alxiong** [comment]
@pbienst thanks for the clarification. 

Oh I'm thinking of building a customized flashcard for my personal use (just a cli), so trying to learn how does existing solutions for paced repetition work. :)
