### ISSUE TITLE
Sync always fails on android app

### ISSUE THREAD

**Issue by girlsim** [mnemosyne-proj/mnemosyne#160]
Running mnemo desktop on Windows 10, every time I try to sync from the app it fails and I have to do a full sync.

It used to work fine but stopped working eventually and has been 100% repro since.
Let me know if I can get you any other info

**Comment by pbienst** [comment]
What is the error message? 

Did you change anything in your networking setup (router settings, firewall,...)

**Comment by girlsim** [comment]
I'm on a different router than I was before (I moved), but this started without me changing anything that I remember (it was a while ago, unfortunately).

Here are the errors I see, in order:
Popup on the PC client: "Sync failed, the next sync will be a full sync."
Second popup on the PC client:
`Traceback (innermost last):
 File "openSM2sync/server.py", line 422, in put_client_log_entries
KeyError: 'o_id'`
Popup on the mobile client: "Sync failed, the next sync will be a full sync."
Second popup on the mobile client: "internal server error"

**Comment by pbienst** [comment]
Are you sure you are on the latest version from our website? There was an
error like this on older versions...

Peter

**Comment by girlsim** [comment]
Double checked and I was on 2.6.1. Going to guess that version still had this issue.
Thanks!
