### ISSUE TITLE
Sync failing on android app

### ISSUE THREAD

**Issue by girlsim** [mnemosyne-proj/mnemosyne#162]
Hi!

Every time I try to sync, I'm getting a "sync failed" error.
This was happening to me before, but it was because my desktop client was out of date. Updating to the 2.7.1 client fixed it for a while, but it started happening again (though I assume it's a different root cause).
My network settings and hardware haven't changed.
The desktop client doesn't show an error, but I have screenshots of the error on the mobile client: 
https://media.discordapp.net/attachments/312262834195267586/719442999591043112/Screenshot_20200607-234756.png
https://media.discordapp.net/attachments/312262834195267586/719442999045521438/Screenshot_20200607-234759.png
Let me know what other info I can get you to help investigate--it seems to be a pretty consistent repro as long as I have changes on at least one of the two clients.

**Comment by pbienst** [comment]
Hi,

I'm afraid you're not the only one to report this, but on my devices the
sync only fails occasionally if I'm in a location with bad WIFI reception.

As such, it will be extremely difficult for me to track down what's going
on. The only possibility is if you can indeed reproduce this consistently
and I send you a special debug client to help track this down. Are you
using Windows?

Cheers,

Peter

**Comment by girlsim** [comment]
Yup--Windows 10.
Port, username, password, etc are all ok: The sync will run partially before failing. When I run it again, it will succeed if I accept the prompt to do a full sync. Password is not empty.
It occurs to me that I have both an ethernet and a wireless connection...I wonder if it's getting mixed  up between the two of them. I'll experiment with turning wifi on/off and see if I can/can't repro like that 🤔

**Comment by pbienst** [comment]
Try this version:
https://www.dropbox.com/s/pb0l267ehrngqnj/mnemosyne-2.7.1b-setup.exe?dl=0

It disables a numerical progress bar on the sync server. I've seen that a fast numerical progress bar sometimes causes crashes.

**Comment by pbienst** [comment]
I heard from the mailing list that the new version no longer suffers from these errors, so I'm closing this and uploading the new version to the website.

**Comment by girlsim** [comment]
Hey! I was never able to repro the issue again, so I do indeed believe the update fixed it for me. Thank you :)
