### ISSUE TITLE
https://mnemosyne-proj.org/help/syncing

### ISSUE THREAD

**Issue by DrOteonu-Nanquanu** [mnemosyne-proj/mnemosyne#167]
Typo in last sentence of https://mnemosyne-proj.org/help/syncing

"Also, make sure that you don't leave two copies of Mnemosyne running at the same time on different machines, as this will corruption and issues with the science log upload."

**Comment by pbienst** [comment]
Fixed, thanks!

**Comment by DrOteonu-Nanquanu** [comment]
You're welcome ! Thanks for the wonderful spaced repetition project!
