### ISSUE TITLE
(Android) switching card sets while in "learn ahead of schedule" breaks scheduled card counter

### ISSUE THREAD

**Issue by girlsim** [mnemosyne-proj/mnemosyne#173]
This one is pretty silly.
Steps:
- Create card sets A and B
- Sync to the Android app
- Go through all of set A
- Hit the "learn ahead of schedule" prompt
- Switch to set B
- Review some cards
observed: the "scheduled" counter does not update. If you switch to set A and back to set B it will update once, but will continue to not update as you continue to review.
Fixed by restarting the app.

**Comment by pbienst** [comment]
Thanks, the fix will be in the next release.
