### ISSUE TITLE
Android app rendered unusable by archiving

### ISSUE THREAD

**Issue by girlsim** [mnemosyne-proj/mnemosyne#179]
Every time I open the Android app, it displays the "About to archive old logs..." message. If I hit "ok, proceed", it shows this error:
![Screenshot_20201215-005432](https://user-images.githubusercontent.com/10914473/102195963-1dadf400-3e74-11eb-907e-8f1875ab5857.png)
If I hit "ok" on that, it shows the "archiving..." spinner for a minute or two, then pops the "about to archive old logs..." message again.
This cycle seems to continue indefinitely, so I'm not able to do anything else with the app.
My app is version 2.3.1-arm64. There does not appear to be a newer version available.
If there isn't any immediate way to fix this, can I at least retrieve my progress by copying some files somewhere?

**Comment by girlsim** [comment]
It looks like it's just failing to edit the sqlite DB, so my first thought was that my phone was out of space, but that's not the case.
I did accidentally close the app while it was archiving old logs a few weeks ago, so I'm wondering if somehow that put the DB in a bad state and now it can't update it? But I would expect that if that were the case it would have errored before now. And even if that is the case I'm not clear on why it always tries to archive on startup now.

**Comment by girlsim** [comment]
Upon some further experimentation, I've noticed that there are a couple of different errors it will pop (always from the same line in the same file):
- "disk I/O error"
- "database archive is already in use" (seems to be the most common)
- I believe there was one other, but I haven't been able to reproduce it again.

**Comment by pbienst** [comment]
Yes, turning off the phone while archiving will have caused this.

You can just delete your database and resync from the server.

(alternatively, you could try opening your phone's default.db using the desktop app, but I'm not sure that will help.)

You can also see if there are automatic backups inside the 'mnemosyne/backups' directory.

**Comment by girlsim** [comment]
Oof. My server is several months behind the app.
Is there any way to preserve my progress from the time between when I shut off the phone before, or is it just lost?

**Comment by girlsim** [comment]
For posterity in case anyone has the same issue and ends up here: I was able to fix the issue while preserving my local progress by
- Replacing the server's default.db with a copy of the local one
- Deleting the local default.db
- Resyncing.
like Peter suggested. 
Thank you!
