### ISSUE TITLE
Use custom context menu for the review widget Q/A

### ISSUE THREAD

**Issue by three-comrades** [mnemosyne-proj/mnemosyne#18]
When reviewing cards, a right click on the question/answer areas brings up the standard (?) 'browser' context menu. IMHO, the actions it provides don't make much sense for mnemsnosyne:

- back/forward
- reload
- view page source

In a first step, I'd like to look into disabling all of those, as they currenty don't work in a useful way (at least as far as I can see). Second, I would love to have an edit entry instead. Currently, if I want to make a quick correction I have to open the card browser, search for the card and then edit it, which I find cumbersome.

Do you think that's worthwhile trying out?

P.S.: do you prefer to discuss such ideas on the mailing list or in the issue tracker?

**Comment by pbienst** [comment]
Feel free to go for it! There was something like that when we still used webkit in Qt 4, but with the forced migration to Webenginview, this was originally not supported. Could be that's changed in the latest Qt version.

No problem to discuss these issues here.
