### ISSUE TITLE
Mobile app getting stuck archiving old logs

### ISSUE THREAD

**Issue by girlsim** [mnemosyne-proj/mnemosyne#183]
Hey, I'm back with another random mobile bug.
This is similar to the last one I reported, except with that one I had accidentally closed the app during the archiving so it was expected that it got in a messed up state. In this case I had not closed it during the archiving: The first time the archiving prompt showed up, it failed in this way.
What happens: When I open the app, it shows the "archiving old logs" prompt. If I hit OK it immediately fails with an error. After I dismiss the error, it shows the "archiving..." spinner for ~1 minute, then silently fails and shows the "archiving old logs" prompt again.
Here are screenshots of the two errors it was showing:
https://media.discordapp.net/attachments/312262834195267586/821551471085748234/Screenshot_20210316-174711.png
https://media.discordapp.net/attachments/312262834195267586/821551471546859540/Screenshot_20210316-174617.png

I was able to work around this by copying my mobile db into the desktop app's data folder, deleting the mobile app's db, and then resyncing from desktop like you suggested last time.
Before doing this I tried swapping out the mobile db for one of its backups (even ones from several days ago) worked, interestingly.
I don't know if this is super important to fix since it can be worked around, provided it isn't being caused by some bigger underlying issue, but it would be nice to be able to dismiss the "archiving old logs" prompt without starting the archive so I could sync from desktop immediately instead of having to copy the dbs around manually.

**Comment by pbienst** [comment]
I'm afraid the disk IO error points to some problem with your storage. This could be a hardware issue. Since I cannot reproduce this on my devices, I'm not sure there's anything I can do about this from my side...
