### ISSUE TITLE
Menmosyne tries deleting 1:1s.jpeg file and fails

### ISSUE THREAD

**Issue by matkoniecz** [mnemosyne-proj/mnemosyne#195]
```
An unexpected error has occurred.
Please forward the following info to the developers:

Traceback (innermost last):
  File "/usr/lib/python3/dist-packages/mnemosyne/pyqt_ui/delete_unused_media_files_dlg.py", line 30, in accept
    self.database().delete_unused_media_files(self.unused_media_files)
  File "/usr/lib/python3/dist-packages/mnemosyne/libmnemosyne/databases/SQLite_media.py", line 222, in delete_unused_media_files
    os.remove(expand_path(filename, self.media_dir()))
 FileNotFoundError: [Errno 2] No such file or directory: '1:1s.jpeg'
```

as workaround I have deleted it manually

https://github.com/mnemosyne-proj/mnemosyne/blob/8c1db97f33b468b90683ae881b87e2736e496741/mnemosyne/libmnemosyne/databases/SQLite_media.py#L222

Creating an empty `1:1s.jpeg` file in `~/.local/share/mnemosyne/default.db_media` replicated this issue

**Comment by pbienst** [comment]
The issue is the colon in the filename, which is illegal under Windows...

**Comment by matkoniecz** [comment]
I am running Mnemosyne on Linux where I can have `?:\*.jpg` file.

![screen](https://user-images.githubusercontent.com/899988/128712822-e043e48b-4109-4a0a-9565-7ce45d100560.png)

**Comment by pbienst** [comment]
I don't have easy access to a Linux machine with X, so I can't easily check what's going on myself. Patches welcome, though...
