### ISSUE TITLE
Unexpected error when browsing cards

### ISSUE THREAD

**Issue by danparshall** [mnemosyne-proj/mnemosyne#197]
Hi folks,

I'm on Linux Mint 19.3, I installed mnemosyne using the "Software Manager" tool.  I started the program, and began adding cards.  I went to lunch, and upon returning I couldn't remember where I'd left off, so I closed the "Add cards" window (not sure if I clicked "X" in the corner, or used "Exit").

Now, anytime I try to browse cards (whether from the dropdown menu, or using Control-B), the "Browse cards" window opens, but then an error message immediately appears, stating:

> An unexpected error has occurred.
>Please forward the following info to the developers:
>
>Traceback (innermost last):
>  File "/usr/lib/python3/dist-packages/mnemosyne/pyqt_ui/browse_cards_dlg.py", line 263, in paint
>    style.subElementRect(QtWidgets.QStyle.SE_ItemViewItemText, option)
> TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments

Trying to click "OK" or "X" closes the error window, but then it immediately reopens; at that point things are caught in a loop, and I can't return to the main window.  The only way to exit the program is to kill it from the command line.

**Comment by pbienst** [comment]
I seem to remember this error from a previous version. Probably Mint doesn't package the latest version, so you'll have to download the tarball and follow the instructions inside to install it.
