### ISSUE TITLE
Mnemosyne 2.5: ImportError: cannot import name 'QtWebEngineWidgets'

### ISSUE THREAD

**Issue by grberta** [mnemosyne-proj/mnemosyne#20]
Hallo,
when entering mnemosyne I get the following error message:
---------message----------------
An unexpected error has occurred.
Please forward the following info to the developers:

Traceback (innermost last):
  File "/usr/local/bin/mnemosyne", line 4, in <module>
    __import__('pkg_resources').run_script('Mnemosyne==2.5', 'mnemosyne')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/Mnemosyne-2.5-py3.6.egg/EGG-INFO/scripts/mnemosyne", line 147, in <module>
    from PyQt5 import QtWebEngineWidgets  # Needs to happen first for some reason.
 ImportError: cannot import name 'QtWebEngineWidgets'
----------message-------------

My system is 
Linux xxxx 4.13.0-1-amd64 #1 SMP Debian 4.13.4-2 (2017-10-15) x86_64 GNU/Linux

How can I solve the problem?

Thank you very much.

**Comment by pbienst** [comment]
QtWebEngineWidgets is not installed, please install that package first.

**Comment by grberta** [comment]
I have installed
sudo apt-get install qtwebengine5-dev

This file exists:
/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets/QtWebEngineWidgets

I repeated the initialization with:
sudo python3 setup.py install

Result: The same error message !

**Comment by pbienst** [comment]
I'm afraid this is more a Debian issue than an Mnemosyne issue. Perhaps you can ask for help on a Debian forum? Perhaps installing Mnemosyne's Debian package helps to pull in the required dependencies in a correct way?

**Comment by grberta** [comment]
Mnemosyne is no longer listed in the package lists. 
I try it in a Debian forum.

**Comment by three-comrades** [comment]
Are you saying mnemosyne is not in the Debian repositories any more? Hm, I wonder why. I guess I'll have a look.

**Comment by three-comrades** [comment]
@grberta are you using Debian testing? If so, according to the package [tracker](https://tracker.debian.org/pkg/mnemosyne), Memosyne got removed from testing because of some undocumente javascript code in the docs. I have no idea what that means. If you use testing, maybe ask the maintainer?

**Comment by pbienst** [comment]
In any case, the package in that page still seems to refer to 2.4, which won't help you...

**Comment by grberta** [comment]
@three-comrades Since July 7 2016 there is this error at program startup:
"ImortError: connot import name QtWebKit"
Since then I couldn't use the program any more, no matter if in the Debian stable or the testing version.

**Comment by grberta** [comment]
Mnemosyne works now, Debian packages were missing.
I don't remember which ones I have installed additionally, here are all now installed with "pyqt5"

aptitude search pyqt5 | grep -e '^i'
i  pyqt5-dev - Entwicklungsdateien für PyQt5
i  python-pyqt5 - Python-2-Anbindungen für Qt5
i  python-pyqt5.qtsvg - Python 2 bindings for Qt5's SVG module
i  python-pyqt5.qtwebkit - Python 2 bindings for Qt5's WebKit module
i A python3-dbus.mainloop.pyqt5 - D-Bus Qt main loop support for Python 3
i A python3-pyqt5 - Python-3-Anbindungen für Qt5
i A python3-pyqt5.qtmultimedia - Python 3 bindings for Qt5's Multimedia module
i A python3-pyqt5.qtopengl - Python 3 bindings for Qt5's OpenGL module
i  python3-pyqt5.qtsql - Python 3 bindings for Qt5's SQL module
i A python3-pyqt5.qtsvg - Python 3 bindings for Qt5's SVG module
i A python3-pyqt5.qtwebchannel - Python 3 bindings for Qt5's WebChannel module
i  python3-pyqt5.qtwebengine - Python 3 bindings for Qt5's WebEngine module
i A python3-pyqt5.qtwebkit - Python 3 bindings for Qt5's WebKit module

**Comment by grberta** [comment]
I mean, it was these packages:
python3-pyqt5.qtsql
python3-pyqt5.qtwebengine

**Comment by CoderLoveMath** [comment]
So Thank you!
