### ISSUE TITLE
Feature Request: make  Google Translate and Google Text to Speech optimal dependencies 

### ISSUE THREAD

**Issue by Lukas1818** [mnemosyne-proj/mnemosyne#200]
I think many users did not need this features. Furthermore the associated packages [python:googletrans](https://repology.org/project/python:googletrans/versions) and [python:gtts](https://repology.org/project/python:gtts/versions) are not part of many linux distributions.
It would also be much easier to create and maintain a [mnemosyne](https://repology.org/project/mnemosyne/versions) package, so mnemosyne will hopeful be available at more distributions.
Some distribution like debian has already apply their own patches to disable this features.

Because of this I would be nice if  this packages will be only optimal.

**Comment by pbienst** [comment]
Whether or not many people use these features is of course a matter of debate :-) 

I do believe it's the responsibility of the distributions here to take any actions they see fit, rather than Mnemosyne having to cater to the common denominator.

**Comment by alexdewar** [comment]
@pbienst Hi! Thanks for producing Mnemosyne :-)

I'm the maintainer for the Arch Linux AUR package. The issue we're having at the moment is that the ``googletrans`` package is broken, which unfortunately also means that users cannot install or use Mnemosyne, regardless of whether or not they want this functionality. Mnemosyne currently won't start without this package being present. It could most easily be made optional by turning this fatal error into a warning instead (i.e. wrapping the ``import googletrans`` in a ``try``/``except`` block. I'm happy to put in a PR if you don't have time.

**Comment by Lukas1818** [comment]
I had create a pull requests, which does make both optional: https://github.com/mnemosyne-proj/mnemosyne/pull/201

**Comment by pbienst** [comment]
I have committed it, but I wouldn't be surprised if in the future we get support requests about why these features are not present, since there's not even a console warning message now...

**Comment by Lukas1818** [comment]
I can add a warning, if you wish. That is no problem.

**Comment by alexdewar** [comment]
Thanks both. That's much appreciated.
