### ISSUE TITLE
On Android client show info about sync message not only on the first opening but always if it has 0 cards

### ISSUE THREAD

**Issue by matkoniecz** [mnemosyne-proj/mnemosyne#204]
I started once, got message, left to configure something else and opened again. This time no message was shown, just confusing empty screen.

**Comment by pbienst** [comment]
The idea is that you at least read the message before going away :-) That will tell you that you need to sync to get your database.

**Comment by matkoniecz** [comment]
> The idea is that you at least read the message before going away :-)

Though on phone it is relatively normal to leave app and move somewhere else (in this case I got notification that something that I was waiting for in work become available so I moved to higher priority thing)

And unlike on computer the message was not there when I left.

In addition, this is sufficiently complex that need to follow it in steps or recheck message seems normal to me.
