### ISSUE TITLE
It is not clear how user should start sync server.

### ISSUE THREAD

**Issue by matkoniecz** [mnemosyne-proj/mnemosyne#205]
On going to Mnemosyne settings and enabling "allow to sync..." checkbox nothing happens and "Sync server NOT running".

Not sure is it some bug or should I just restart Mnemosyne/computer.

Posting it here as recommended in Android review response.

**Comment by matkoniecz** [comment]
OK, on pressing "yes" it gets saved. Maybe replace "Sync server NOT running" by

> Sync server NOT running, allow other devices to sync and press OK to save settings

?

**Comment by pbienst** [comment]
You do indeed need to apply the settings, as is customary in these types of dialogs.
