### ISSUE TITLE
No sync progress shown

### ISSUE THREAD

**Issue by matkoniecz** [mnemosyne-proj/mnemosyne#206]
App is still showing "Rch: 0 Not mem.: 0 Act: 0"

No progress bar or error message shown.

> Dynamically creating media files...

shown on desktop, with a fake progress bar (just animated fully filled bar). Not showing which media files are processed.

There is no indicator anywhere is progress stuck or progressing. Maybe at least show which media file is being processed in progress box on computer? Or maybe show some kind of progress box in app?

**Comment by pbienst** [comment]
There reason there are fake progress bars is because of a bug in Qt which sometimes causes crashes with true progress bars. Just be patient and wait for the progress bar to disappear...
