### ISSUE TITLE
Efficient Card Editing

### ISSUE THREAD

**Issue by jmehne** [mnemosyne-proj/mnemosyne#21]
I was recently thinking about editing cards. Two things:

1. The built-in editor: the built-in editor is very clean, which I like a lot. Unfortunately, it is not discoverable at all. I.e., without reading the docs (and who does nowadays ...), a user doesn't really know that they actually can format their cards (edit: that may not be true - there is probably already a hint in the tips dialogue or what it's called). In my opinion, the edit/add card widget could do with a very minimal additional toolbar that offers basic formatting and a subtle hint to the docs. Such a *horizontal* toolbar could include:

- bold
- italics
- list-drop-dow: enumerated and normal
- media-drop-down: image, video, etc.
- misc-drop-down: table, code/monospace, latex, 'more' (=link to help)

2. External editors: cards are plaintext and there are more than enough great editors out there. It would be nice if Mnemosye could somehow pipe the source of a card to an external editor and read/re-import the card automatically. External editors can provide proper syntax highlighting and come with all the tools necessary. Personally, I would use `vim` for example.

Are these things you could imagine to be shipped as built-in or is that plugin territory?

**Comment by pbienst** [comment]
Nothing against it, but I think it should be either a plugin or a configuration option.

BTW, many years ago, I had a prototype of this, but I couldn't get it to look nice and unobtrusive. But perhaps a fresh approach could be helpful.

**Comment by davidermined** [comment]
re 1:
Someone who would be savy enough to install a plugin or a config option would not need it though, because he'd already know about all the formatting options and shortcuts and be comfortable formatting things with angular brackets. This wouldn't solve the discoverability issue.

**Comment by three-comrades** [comment]
If the default is `off`, then yes. But let's see what it looks like first, although I won't have time for this before the christmas break.

**Comment by pbienst** [comment]
Cleaning up some old issues. Feel free to reopen this if you start working on this again.
