### ISSUE TITLE
fatal error: 'cpython/pymem.h' file not found on building Andoid app

### ISSUE THREAD

**Issue by matkoniecz** [mnemosyne-proj/mnemosyne#210]
I want to run Android app in emulator to debug https://user-images.githubusercontent.com/899988/141748994-685cbd29-5389-4e48-9d4e-ae42c236e5ca.png

https://github.com/mnemosyne-proj/mnemosyne/blob/master/README.md seems to have no info how to build Android, so I followed standard solution: opened https://github.com/mnemosyne-proj/mnemosyne/tree/master/mnemosyne/android folder in Android Studio and order it to run app

This resulted in

```
In file included from /home/mateusz/Desktop/tmp/mnemosyne/mnemosyne/android/app/src/main/cpp/pybridge.c:13:
In file included from /home/mateusz/Desktop/tmp/mnemosyne/mnemosyne/android/dependencies/python/include/arm64-v8a/Python.h:85:
In file included from /home/mateusz/Desktop/tmp/mnemosyne/mnemosyne/android/dependencies/python/include/arm64-v8a/pytime.h:6:
In file included from /home/mateusz/Desktop/tmp/mnemosyne/mnemosyne/android/dependencies/python/include/arm64-v8a/object.h:4:
/home/mateusz/Desktop/tmp/mnemosyne/mnemosyne/android/dependencies/python/include/arm64-v8a/pymem.h:142:13: fatal error: 'cpython/pymem.h' file not found
```

**Comment by pbienst** [comment]
The developer instructions for Android are here:

https://github.com/mnemosyne-proj/mnemosyne/tree/master/mnemosyne/android_python
