### ISSUE TITLE
Phantom card that crashes Mnemosyne

### ISSUE THREAD

**Issue by enifmada** [mnemosyne-proj/mnemosyne#211]
Hi,

I seem to have encountered a bug somewhere in the cloze deletion card maintenance process. The steps leading to the discovery of this were as follows:
I did the majority of my scheduled cards through the Mnemosyne app on a phone running Android 9. At some point, I synced my cards to my computer (Windows 10, Mnemosyne version 2.8), and noticed that my phone's count of my remaining scheduled cards was one higher than my computer's. After confirming that this was not due to which card set was active, certain cards being picked up as inactive, etc., I figured I would just finish my scheduled cards and see what was left on my phone. 

The last scheduled card on my phone did exist in my computer's database, though two things were strange about it:
1. My computer's database indicated that its next scheduled rep was tomorrow, rather than today.
2. The card was a duplicate of a cloze in another card - i.e. I had two cloze cards generated from "[X] is related to [Y]", and this strangely-behaving card was a copy of the card whose answer was X, supposedly created almost a year later. There was no corresponding copy of the card whose answer was Y.

I deleted the original two cards, hoping that doing so would also delete this "phantom card", and received the following error message twice, followed by Mnemosyne crashing.
<img width="481" alt="mnemosyne_error" src="https://user-images.githubusercontent.com/8041675/147862496-2edd4d3d-8d13-4d63-b93a-b71a1d469f3e.png">
Mnemosyne restarted normally, but upon searching for the text in the card or manually scrolling to the card in the browse window, I received the same error message followed by Mnemosyne crashing. I then re-added the two previously deleted cards in the cloze, but the same behavior of crashing when attempting to display the phantom card remained. 
Lastly, I opened a backup, which contained and displayed normally the two normal cards and the phantom card. In the backup, I attempted to delete all three cards at once (rather than just the original cloze), and experienced the same behavior as above, with the same error message.

Other information that may be relevant:
- I occasionally "undo" an erroneous correct grade when doing scheduled cards by deleting and re-writing the left bracket of a cloze (e.g. if I accidentally grade the cloze "X" in "[X] is related to [Y]" as correct, I edit the card to say "X] is related to [Y]" then restore it to "[X] is related to [Y]", which generates a new card with answer "X" that is Yet to Learn). This has never caused an issue prior to today.
- The "phantom card" behaved strangely when I tried "undoing" the cloze it was a copy of via the delete-and-reinsert-left-bracket method; doing this technique on a normal set of cloze cards doesn't affect the other clozes, but the phantom card switched its answer from cloze X to cloze Y.

The backups are perfectly useable so this is not a particularly pressing issue, I've just never seen anything like this in my 8 years using Mnemosyne!

Thanks!

Best,
Adam

**Comment by pbienst** [comment]
Thanks for the report! If your backups weren't usable, I would have offered to manually fix your database, but that doesn't seem to be necessary now.

With regards to fixing the root cause: I'm afraid that this seems to be a very rare corner case, which would require knowledge of the exact steps that caused the problem to appear. So, if you ever encounter this again, do reopen this report, mentioning your exact editing steps.
