### ISSUE TITLE
Support narrow (phone) screens

### ISSUE THREAD

**Issue by mexon** [mnemosyne-proj/mnemosyne#212]
These days I use Mnemosyne almost entirely on a pinephone, with a screen resolution of 360x720.  It was unusable until I made the following patches:

```
diff -r ../Mnemosyne-2.7.3/mnemosyne/pyqt_ui/main_wdgt.py Mnemosyne-2.7.3/mnemosyne/pyqt_ui/main_wdgt.py
27d26
<         self.setFixedSize(360, 620)
diff -r ../Mnemosyne-2.7.3/mnemosyne/pyqt_ui/ui_review_wdgt.py Mnemosyne-2.7.3/mnemosyne/pyqt_ui/ui_review_wdgt.py
18c18
<         ReviewWdgt.resize(229, 259)
---
>         ReviewWdgt.resize(529, 259)
```

With those in place, the application is (surprisingly) just about usable, although for card management I `scp` the database to my Mac and `scp` it back when I'm done.  Still, even without a mouse or the ability to move and resize windows, menus and buttons generally work fine.  The app is launchable from the phone home screen.

I don't know anything about PyQT and can't really contribute maintainable code for this.  However, it seems clear that much smaller resolutions still provide enough space for core functionality, so it should be possible to automatically adapt when the screen is unusually small.

The only trick seems to be adjusting for the status bar at the top.  Other than that though, I don't think this would actually require a phone to develop.  Just ensure that the UI responds correctly to unusually small screens.

**Comment by pbienst** [comment]
Glad you got this working to your liking, but I suspect this is a very niche use case. Unless there's more demand for this, or unless there's more maintainable code for this, I propose you just keep using these patches locally.

**Comment by Eloitor** [comment]
I discovered Mnemosyne while searching  a space repetition software that works on the pinephone. Installing it in archarm didn't work. The installation  in Mobian was unusable, and I finally succeeded using bedrocklinux to install the debian package of Mnemosyne on archarm. This took some time to figure out... but I love it now.

I'm trying to package Mnemosyne for PostmarketOS (based on alpine linux), and it would be nice if smaller screens were supported by default. It would make it easier to package it for other distributions.

This is the only SRS that I know that works well on the pinephone, and it has more functionality than the android app.

**Comment by mexon** [comment]
How exciting!  This definitely counts as "more demand": there is now a demand of 2 😉

To update my original comment: I no longer need to scp files around for card management.  I found that I can rotate the screen to landscape, and that gives me enough horizontal space to scroll and select the tag I want to activate.  But there's then not enough vertical space to select the OK button, so I rotate back to portrait to click that button.

To get more maintainable code, we'd need someone who understands PyQT.  I understand Python but not PyQT.  Given a few hints I could probably make the changes myself.
