### ISSUE TITLE
Leading whitespace on cards is stripped

### ISSUE THREAD

**Issue by frozencemetery** [mnemosyne-proj/mnemosyne#213]
Hi, I'm trying to make some cards that use whitespace for alignment.  A simplified version could be something like:

```
1 2 3
  ^
 this one
```

However, mnemosyne seems to display the card stripping the leading whitespace - it becomes:

```
1 2 3
^
this one
```

I verified that the cards are correctly (i.e., with the requested whitespace) stored in the db, and I can even edit them as such.  It seems to be purely a display issue.

I'm running mnemosyne-2.8+ds1-2 from Debian.  I did attempt to run from git, but ran into QT errors.  Thanks

**Comment by pbienst** [comment]
You can use the html for non-breaking space:	&nbsp;

**Comment by frozencemetery** [comment]
Thanks, that seems to work.  I'm still left wondering what the logic is for stripping spaces to begin with is, though.  The current behavior seems like an accident - cards are stored with the spaces intact, and of course they show in the editor.

That said, I totally understand not wanting to dig into it - I've already given up on that too, so it's not like I'm about to propose a fix either :)

**Comment by pbienst** [comment]
The logic is that the card text is interpreted as html, and html ignores extra spaces.
