### ISSUE TITLE
Hardcoded matplotlib font dependency warnings

### ISSUE THREAD

**Issue by miKa-pyon** [mnemosyne-proj/mnemosyne#217]
`pyqt_ui/statistics_wdgts_plotting.py` creates an unnecessary dependency by hardcoding the "Arial" font parameter for matplotlib.

This spams logs with several
```
findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
```
everytime statistics are displayed and overrides default matplotlib font settings.

Not explicitly setting the parameter solves the issue:
```
diff old/statistics_wdgts_plotting.py pyqt_ui/statistics_wdgts_plotting.py
60,61d59
<         else:
<             rcParams['font.sans-serif'] = ["Arial"]
```
Only tested this on Linux.

**Comment by pbienst** [comment]
Fixed, thanks!
