### ISSUE TITLE
ValueError when launching the application

### ISSUE THREAD

**Issue by FBergeron** [mnemosyne-proj/mnemosyne#218]
Hi,

Today, I can no longer use Mnemosyne.  I have this error when I launch the application:

An unexpected error has occurred.
Please forward the following info to the developers:

```
Traceback (innermost last):
  File "/usr/bin/mnemosyne", line 277, in <module>
    mnemosyne.initialise(data_dir=data_dir, filename=filename,
  File "/usr/lib/python3/dist-packages/mnemosyne/libmnemosyne/__init__.py", line 410, in initialise
    self.activate_components()
  File "/usr/lib/python3/dist-packages/mnemosyne/libmnemosyne/__init__.py", line 499, in activate_components
    self.component_manager.current(component).activate()
  File "/usr/lib/python3/dist-packages/mnemosyne/libmnemosyne/logger.py", line 23, in activate
    self.archive_old_log()
  File "/usr/lib/python3/dist-packages/mnemosyne/libmnemosyne/logger.py", line 186, in archive_old_log
    index = self.log_index_of_last_upload() + 1
  File "/usr/lib/python3/dist-packages/mnemosyne/libmnemosyne/logger.py", line 163, in log_index_of_last_upload
    user, machine = user_and_machine.split("_")
 ValueError: too many values to unpack (expected 2)
```

I'm using mnemosyne 2.7.3+ds1-2 on Debian 11 (stable).

I hope you can fix that.  I think I have almost 4000 cards in my database.

**Comment by gbear605** [comment]
How did you install Mnemosyne? Using your distribution’s package manager or manually?

Either way, you might try upgrading to the latest version (2.8) and see if that resolves the issue.

**Comment by gbear605** [comment]
Also before you do so, it wouldn’t hurt to backup your database (see the instructions at https://mnemosyne-proj.org/help/backups.php) just in case. There shouldn’t be any risk of data loss, but it never hurts.

**Comment by pbienst** [comment]
After upgrading, please also check the history folder in your data directory (default is ~/.local/share/mnemosyne). It should only contain files like <long id string>.bz2 and 'uploaded2'

**Comment by FBergeron** [comment]
I installed mnemosyne using my distribution package.

I tried to install mnemosyne 2.8 but I get this error when I launch it:

```
Log body:
 An unexpected error has occurred.
Please forward the following info to the developers:

Traceback (innermost last):
  File "/usr/bin/mnemosyne", line 150, in <module>
    from PyQt5 import QtWebEngineWidgets  # Needs to happen first for some reason.
 ImportError: /home/fred/.local/lib/python3.9/site-packages/PyQt5/QtCore.abi3.so: undefined symbol: _ZdlPvm, version Qt_5

An unexpected error has occurred.
Please forward the following info to the developers:

Traceback (innermost last):
  File "/usr/bin/mnemosyne", line 150, in <module>
    from PyQt5 import QtWebEngineWidgets  # Needs to happen first for some reason.
 ImportError: /home/fred/.local/lib/python3.9/site-packages/PyQt5/QtCore.abi3.so: undefined symbol: _ZdlPvm, version Qt_5
An unexpected error has occurred.
Please forward the following info to the developers:

Traceback (innermost last):
  File "/usr/bin/mnemosyne", line 150, in <module>
    from PyQt5 import QtWebEngineWidgets  # Needs to happen first for some reason.
 ImportError: /home/fred/.local/lib/python3.9/site-packages/PyQt5/QtCore.abi3.so: undefined symbol: _ZdlPvm, version Qt_5

```
I exported my data and imported them on my  mac (that uses mnemosyne 2.7.3) and it launches and works properly.  My data seem ok.  Still, I would like to keep using my Debian machine if it's possible. So if you can help with the issue above, that would be very appreciated.

**Comment by pbienst** [comment]
Qt and/or QtWebEngineWidgets do not seem to be properly installed. However, I'm afraid that's a Debian issue, and not a Mnemosyne one. If trying to reinstall Qt WebEngine does not work, I suggest asking on a Debian forum..

**Comment by FBergeron** [comment]
Ok, thanks anyway.
