### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by rep0** [mnemosyne-proj/mnemosyne#22]
Upon clicking  'Exit' in the 'File' menu,  the following output was printed:
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
An unexpected error has occurred.
Please forward the following info to the developers:

Traceback (innermost last):
  File "/home/\<user\>/.py_envs/mnem25/lib64/python3.6/site-packages/Mnemosyne-2.5-py3.6.egg/mnemosyne/pyqt_ui/main_wdgt.py", line 76, in controller_heartbeat
    self.controller().heartbeat()
  File "/home/\<user\>/.py_envs/mnem25/lib64/python3.6/site-packages/Mnemosyne-2.5-py3.6.egg/mnemosyne/libmnemosyne/controllers/default_controller.py", line 52, in heartbeat
    if not self.database().is_loaded() or \
 AttributeError: 'NoneType' object has no attribute 'is_loaded'
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Context:  I'm in the habit of leaving Mnemosyne running for weeks at a time.  It was during one such long run that no new cards were presented for several days, which is unusual, and made me suspect something was wrong.  So I shut down Mnemosyne, and then the error above occurred.

After starting Mnemosyne again, everything seems to be fine.  To be honest, I'm reporting this only to honor the request to "Please forward the following info the the developers..."

**Comment by pbienst** [comment]
This is indeed harmless, but I've committed a patch to prevent this from reoccuring.
