### ISSUE TITLE
Web client - sound is not played

### ISSUE THREAD

**Issue by jooseef** [mnemosyne-proj/mnemosyne#222]
Hello :-)

When I use the web client and click the play button, I hear no sound.
The web server runs on Windows 11 and the client on an Android smartphone.
What could be the problem?
Regards J.

**Comment by pbienst** [comment]
A reason could be that your browser does not support audio tags. Anyway, if you're on Android, you're much better off using the Android mobile client.

**Comment by jooseef** [comment]
It does not work, not with Firefox and not with Chrome. How to solve the problem pls?

**Comment by jooseef** [comment]
I think it is an encode/decode server issue. E.g. a sound file with this name cannot be played: du%20z%C3%A4hlst%20-%20%D8%A3%D9%86%D8%AA%20%D8%AA%D8%B9%D8%AF%2C%20%D8%A3%D9%86%D8%AA%20%D8%AA%D8%B9%D8%AF%D9%8A%D9%86.mp3
What can I do?

**Comment by pbienst** [comment]
Just to check, can you try if it works with a simple filename like a.mp3?

**Comment by pbienst** [comment]
And also try with Chrome mobile.

**Comment by jooseef** [comment]
Yes it works with the filename a.mp3
:-O
No idea atm if I can solve the problem or if some additional code for the server is needed. :-/

**Comment by pbienst** [comment]
Can you try with Chrome? 

What is the filename you see on the desktop client? Does it work there?

**Comment by jooseef** [comment]
![test](https://user-images.githubusercontent.com/108878285/177970150-795f52e5-1d70-4891-94de-70d3c370c1e0.jpg)
in the source code of the server-generated html file the name a.mp3 stays the same and it works.

**Comment by jooseef** [comment]
Apparently filenames with arabic letters don't work. For example the file with the name "er zählt - هو يعد.mp3" (without quotes) ist not played. Source code shows er%20z%C3%A4hlt%20-%20%D9%87%D9%88%20%D9%8A%D8%B9%D8%AF.mp3 and here https://www.urldecoder.org/ it is decoded correctly to "er zählt - هو يعد.mp3"

**Comment by jooseef** [comment]
The browser loads the file "a.mp3" with the correct name into the browser-chache.
But for some strange reason the file "er zählt - هو يعد.mp3" get's the file-extension ".html".
So, the filename "er%20z%C3%A4hlt%20-%20%D9%87%D9%88%20%D9%8A%D8%B9%D8%AF.mp3" becomes to
"er%20z%C3%A4hlt%20-%20%D9%87%D9%88%20%D9%8A%D8%B9%D8%AF.mp3.html". 
This may be the reason why the player cannot play it.

![Screenshot 2022-07-08 164359](https://user-images.githubusercontent.com/108878285/178015570-a1a38321-007d-41df-b97b-ac0ef128fd71.png)

![Screenshot 2022-07-08 163720](https://user-images.githubusercontent.com/108878285/178014279-2b1212ce-a3fe-454a-8472-217389c1c093.png)

:-O

**Comment by pbienst** [comment]
This version should fix it:

https://www.dropbox.com/s/f5gwx84vdktpyyx/mnemosyne-2.9-web-setup.exe?dl=0

Thanks for reporting this bug!

**Comment by jooseef** [comment]
Thanks a lot for fixing the bug! Now I can use this great tool also on other devices. :-)

**Comment by jooseef** [comment]
Hi
Sorry, but I encountered another problem. I have a flash card with two sound files. Here as example:
<audio src="Geheimnis - سر.mp3">
<audio src="Geheimnisse - أسرار.mp3">
Unfortunately, only the first sound file is played. The second not. On the pictures you can see the generated source code and the files in the cache.
![Screenshot 2022-07-10 222344](https://user-images.githubusercontent.com/108878285/178161124-b6d80049-bb7d-4fb3-8542-216d5b4b707e.png)

**Comment by pbienst** [comment]
Send me / attach the sound files. I'm currently abroad, but will look into it when I get back in a few weeks.

**Comment by jooseef** [comment]
Oookay, here are some sample files.
[sample files.zip](https://github.com/mnemosyne-proj/mnemosyne/files/9085611/sample.files.zip)

**Comment by pbienst** [comment]
I now remember having looked at this a long time ago. For some strange reason, browsers don't seem to support multiple audio tags, even though I can't see anything wrong with the generated html. The answer is probably to resort to a more complicated javascript framework to handle the audio, but I'm afraid that's not on my todo list...

**Comment by jooseef** [comment]
I'm sorry to hear that.
Thank you for your message.

**Comment by jooseef** [comment]
In my opinion, being able to play multiple files is a fundamental technique that the web server should have. ;-)
I found ways with javascript how to do it.
Here is one way:
 ```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Javascript Playlist</title>
<script>
	var playlist = ["1.mp3", "2.mp3", "3.mp3"]; // Playlist				
	var audioplayer = null; // Audioplayer-object initialized by function init_audioplayer()
	var i = 0; // Index of the playlist
		
	function init_audioplayer()
	{
		audioplayer = document.getElementById("player"); // Get the audioplayer object
		if (audioplayer === null) {throw "html audioplayer does not exist!"; return;}
		if(typeof playlist === "undefined"){throw "filearray does not exist!"; return;}	
		audioplayer.src = playlist[i]; // Set the first source from the playlist for the audioplayer
		
		if( playlist.length > 1) // The fuction play_the_playlist() is only needed, if there's more than one file in the playlist 
			audioplayer.onended = play_the_playlist; // The function play_the_playlist() is called, when an audio has reached the end.
	}
	
	function play_the_playlist()
	{
		i++; // Get the index of the next entry in the playlist
		audioplayer.autoplay = true; // If there are more than one soundfile, they shall be played automatically
		if(i == playlist.length) // If the last element in the playlist is reached, 
		{
			audioplayer.autoplay = false; // then disable autoplay
			i=0; // and set the index to the first playlist entry
		}
		audioplayer.src = playlist[i]; // Set the source from the playlist for the audioplayer
	}
</script> 
</head>

<body>

<h1>Javascript Playlist</h1>

	<audio id="player" controls></audio>  <!-- show the audio player -->
	<script> 
		init_audioplayer(); // Audioplayer initialization
    </script>
	
</body>
</html>
 ```
Here's another way, there's no need of the dynamic playlist-creation in javascript(var playlist = ["1.mp3", "2.mp3", "3.mp3"];).
Instead, the playlist is created from the html source code.
 ```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Javascript Playlist 2</title>
<script>
	
	var audioplayer = null;
	const playlist = document.getElementsByTagName("source"); // Create the playlist from the html source code
	var i = 0;
		 
	function init_player()
	{
		audioplayer = document.getElementById("player");
		if(playlist.length > 1) // If there are more than one playlist, then we need the function play_the_playlist() to be fired when and audio reaches the end
		{
			audioplayer.onended = play_the_playlist;
		}
		audioplayer.src = playlist[i].src; // Set the first source
	}
	
	function play_the_playlist()
	{
		i++;
		audioplayer.autoplay = true;
		if(i == playlist.length)
		{
			audioplayer.autoplay = false;
			i=0;
		}
		audioplayer.src = playlist[i].src;
	}
</script> 
</head>

<body>

<h1>Javascript Playlist 2</h1>

	<audio id="player" controls>
		<source src="1.mp3">
	    <source src="2.mp3">
		<source src="3.mp3">
	 </audio> 
	
	<script> 
		 init_player();
    </script>
	
</body>
</html>
```

Maybe you might be thinking about adding the functionality? Please let me know.
[soundfiles.zip](https://github.com/mnemosyne-proj/mnemosyne/files/9212196/soundfiles.zip)

**Comment by pbienst** [comment]
I always welcome patches :-)

**Comment by jooseef** [comment]
[https://www.youtube.com/watch?v=3WAOxKOmR90](url)

**Comment by jooseef** [comment]
[https://www.youtube.com/watch?v=3WAOxKOmR90](url)
