### ISSUE TITLE
Problem with icons

### ISSUE THREAD

**Issue by itraveller1** [mnemosyne-proj/mnemosyne#234]
After a standard installation, the program does not see its icons. The reason seems to be that the icon search paths are tied to the current working directory.

Possible solution:
```
# Add to main script:
pixmaps_dir = os.path.abspath(__file__ + '/../../../pixmaps')
QtCore.QDir.addSearchPath('icons', pixmaps_dir)

# Add to ui_main_wdgt.py and so on:
icon.addPixmap(QtGui.QPixmap("icons:mnemosyne.png")
```

**Comment by pbienst** [comment]
I guess this is on a Linux setup? I can't test this because I don't have a Linux desktop system. Would you mind making/testing the modifications on your end and then submitting a pull request? Thanks!
