### ISSUE TITLE
Left-align and syntax highlighting for code snippets.

### ISSUE THREAD

**Issue by mediumrarez** [mnemosyne-proj/mnemosyne#237]
Currently, I could insert a code snippet between `<code>..</code>` tags, but this makes it display center-aligned, and without code highlighting. (I could set formatting to left-aligned in Mnemosyne preferences, but this makes all cards left-aligned.)

I request a way to left-align and syntax highlight for code snippets.

**Comment by pbienst** [comment]
You don't need to have the same alignment for all cards. Alignment can be different for each Card Type. So, just create a Card Type called e.g. Code Snippets, and set it to left align.

Adding syntax highlighting is a bit out of the scope of Mnemosyne itself. If it's really important to you, you can paste a screenshot from your editor instead, as a workaround.
