### ISSUE TITLE
Broken Launchpad translations

### ISSUE THREAD

**Issue by three-comrades** [mnemosyne-proj/mnemosyne#26]
We had the problem earlier, but I forgot to follow-up on it, so that we got hit again:

Launchpad currently can't import the git repository, because any merge commit on Github adds a `gpgsig` tag that makes the importer on Launchpad error out. 

[Answer](https://answers.launchpad.net/launchpad/+question/661226) from Colin Watson to my question whether it's possible to use git repositories without importing to bzr:
> It isn't possible yet. It's a gap I'd like to close, and in fact I did start some work on it recently, but there are several things to sort out, not least that we need to work out a good equivalent for the series-linked branch model in git.

So, I guess short-term we can't sign commits (if we want to keep using Launchpad 'stranslations infrastracture) and need to make sure that merge commits don't get signed. So, to fix this problem, it is necessary to:
- rewrite the history again which will invalidate all forks. This is really unfortunate, but there don't seem to be that many forks yet, so ... well, it still sucks.
- make sure merge commits don't get signed automatically. @pbienst do you have a gpg key imported into Github? I can't find an option to disable commit signing per project, so I guess you'd have to delete the public key from your Github account ...
- add a check somewhere on travis that fails if a commit is signed so we don't accidentally merge PR's with signed commits.

**Comment by pbienst** [comment]
I think requiring contributors not to have any gpg key will create unnecessary hurdles...

How about we change the approach completely and have a bzr repository on launchpad with only the 'po' directory. Then every so often I can manually or with a script upload the pot file from git to bzr and download the po files in the other direction.

**Comment by three-comrades** [comment]
Sounds good. I have a toy server running that could run such a script every day or so. Writing a script sounds easy:
- create a git clone as a bare repository and a bzr repository on the server
- The script:
  - pulls from Github
   - copies the `po` directory to the local bzr repository
   - commits to the bzr repository
   - pushes to Launchpad

**Comment by pbienst** [comment]
Actually, I was more thinking along the lines of:

- copy the pot file from the git repository to the bzr one and push to launchpad (if you copy the entire po directory you will overwrite the user contributed translations)
- copy the user contributed *.po files from the bzr repository to git and push to github.

**Comment by three-comrades** [comment]
Let's see if this works. The script:

- pulls from Gtihub master and pushes the pot file to this repository: `lp:~jmehne/mnemosyne-proj/translation`
- launchpad commits the new po files here: `lp:~jmehne/mnemosyne-proj/po-translations.`
- the script copies the po files to git and pushes to a bot account on Github to the `translations` branch. [Click](https://github.com/mnemosynebot/mnemosyne/tree/translations). I use a bot account, because I didn't want to put a copy of my private SSH key on the server.

**Comment by three-comrades** [comment]
Okay, this seems to work.
