### ISSUE TITLE
Feature request: Make grading the answer automatic by asking if he gave the right or wrong answer

### ISSUE THREAD

**Issue by atnapes** [mnemosyne-proj/mnemosyne#266]
Dear mnemosyne developers, this way of grading my answer after each card make mental toil for me because each time after I thought about the meaning of the words I have to mentally switch to the grading mechanism and MAKE A DECISION. while making the decision I have to REMEMBER what was the last time I seen this card to avoid giving a high grade if I recently seen this card and all this distracts me from my goal which is learning the contents of the cards.
Please add this feature that after each answer I just have to tell if my answer was right of wrong and the software do the remaining decisioning.

**Comment by pbienst** [comment]
I'm afraid this is not planned, sorry...
