### ISSUE TITLE
On file permissions

### ISSUE THREAD

**Issue by kuraga** [mnemosyne-proj/mnemosyne#278]
67cc4634259231ff6c0ae322b7e772b7119db227 introduced many file permission changes: `0644` -> `0755`.

Why?

**Comment by pbienst** [comment]
Not sure what happened here, but I don't think it's a big deal?

**Comment by blogdron** [comment]
Correct link

* https://github.com/mnemosyne-proj/mnemosyne/commit/67cc4634259231ff6c0ae322b7e772b7119db227.patch

many files now is executable, for example
```diff
old mode 100644
new mode 100755
diff --git a/po/uz.po b/po/uz.po
```

translation `.po` files no need be executable

**Comment by pbienst** [comment]
Ok, happy to accept a patch here.
