### ISSUE TITLE
Crash on startup with error message

### ISSUE THREAD

**Issue by ChrKn** [mnemosyne-proj/mnemosyne#28]
As the title suggests, Mnemosyne [Desktopclient Windows 8.1 latest version] crashed on startup with the following message (ticket since the message asked me nicely to report it ;)):

![error_message](https://user-images.githubusercontent.com/34199043/33520899-da760854-d7c3-11e7-9f77-24555739a239.png)

Probably just misuse from my side. I started a sync from my android client the moment mnemosyne on windows opened. It might also have corrupted or deleted part of my learning statistics. I have been using the program now for about 2 - 3 years straight with 2 days as maximum downtime on my end. After the crash the statistic page is missing a couple of bars on the left. [Note: I don't care. Just wanted to mention it in case it helps to understand what happened.]

![statistics](https://user-images.githubusercontent.com/34199043/33520900-da973ef2-d7c3-11e7-9932-a04879741c4d.png)

I almost forgot. Before it crashed, it told me something about performing an backup. 

PS.: Otherwise everthing is working fine. Happened once and since then no problems. No complaints from my side if this is just considered a weird glitch that is impossible to reproduce and the ticket therefor closed.

**Comment by pbienst** [comment]
Is this with 2.5 or the test version of 2.6?

**Comment by ChrKn** [comment]
2.5

**Comment by pbienst** [comment]
In 2.6, this part of the code has seen some changes, and I assume this issue will not occur. Still, in case this or something else occurs in 2.6, please open another report.
