### ISSUE TITLE
Deprecated and removed modules in Python 3.13

### ISSUE THREAD

**Issue by SnarkBoojum** [mnemosyne-proj/mnemosyne#284]
Python 3.13 removes some modules which were previously deprecated ([see here](https://peps.python.org/pep-0594/#deprecated-modules)) ; and in particular the cgi module, which is still in use in mnemosyne: `mnemosyne/web_server/web_server.py` and `science_server/cgiupload.py` import it...

**Comment by pbienst** [comment]
Thanks, legacy-cgi can be used instead.
