### ISSUE TITLE
App freezes in preview mode from edit screen when running app in virtualenv

### ISSUE THREAD

**Issue by PrecisionWordcraft** [mnemosyne-proj/mnemosyne#289]
I'm running mnemosyne in a python3 virtualenv on Manjaro.

If I edit a card, then select Preview, the preview appears. However, the app then freezes and must be restarted from the terminal.

**Comment by pbienst** [comment]
Perhaps there is something wrong with the PyQt library install? I don't have access to Manjaro, so I can't help you myself, but perhaps you can contact Manjaro support?
