### ISSUE TITLE
Failed to create OpenGL context

### ISSUE THREAD

**Issue by BardoM** [mnemosyne-proj/mnemosyne#31]
When I try to run Mnemosyne 2.5 in my old netbook (Intel GMA 3150 - Windows 10 Home x86), I get the error message:
--
![image](https://user-images.githubusercontent.com/34427035/33810912-b95f0cb2-de0b-11e7-854f-a80d303f07c6.png)
--
I'm not sure if the windows drivers for 3150 support OpenGL 2.0, I don't think so, but I do have the libraries: libEGL.dll, libGLESv2.dll and d3dcompilaer_47.dll.

**Comment by pbienst** [comment]
Have you tried with the options and alternatives listed at the top of this page?

https://mnemosyne-proj.org/download-mnemosyne.php

Alternatively, you can also try with different values for the '--qt-opengl' command line switch. The options are desktop, angle and software.

**Comment by BardoM** [comment]
Yes, sorry, I didn't say it earlier, but I tried to run Mnemosyne with the parameters:
1) '--qt-opengl=desktop'
2) '--qt-opengl=angle'
3) '--qt-opengl=software'

Option '1' begins the process (I saw it in the task manager) but it dies without showing any message or window.
With options '2' and '3' the OpenGL error message is shown.

**Comment by pbienst** [comment]
Then I'm afraid that unless you can install an updated (OpenGL) graphics driver, the only option is to fall back to the 2.3 series...

**Comment by BardoM** [comment]
After further research I found a solution to get run Mnemosyne in my old computer using Mesa 3D Graphics Library.

If it helps someone, my solution is the following:
1) download **MesaForWindows-17.3.1.zip** from https://fdossena.com/?p=mesa/index.frag
2) unzip and copy **opengl32.dll** where Mnemosyne.exe is.
3) run Mnemosyne with the command line switch **--qt-opengl=desktop**

I hope this helps.
Thanks.

**Comment by pbienst** [comment]
Hi,

Thanks for getting back!

Peter


________________________________
