### ISSUE TITLE
Fast format Plugin doesn't work with the latest version of mnemosyne (v2.6)

### ISSUE THREAD

**Issue by evox777** [mnemosyne-proj/mnemosyne#34]
I get various error messages, most relating to wrong syntax. I think the python version was updated in the latest release but the plugin wasn't updated. Hence the incompatibility.

Thanks,
evox777

**Comment by evox777** [comment]
Thank you. The plugin seems to be working well now. Please consider updating the plugin file on the website if you can.

**Comment by pbienst** [comment]
Until they work out ownership, I've manually edited the description of the plugin file to provide a link to the new code.
