### ISSUE TITLE
I'm unable to complete the python command shown in the README

### ISSUE THREAD

**Issue by iambumblehead** [mnemosyne-proj/mnemosyne#38]
I'm unable to complete the python command shown in the README
```bash
~/software/mnemosyne$ sudo python setup.py install
[sudo] password for bumble: 
  File "setup.py", line 22
    "Changes to this script", file=ofi)
                                  ^
SyntaxError: invalid syntax
~/software/mnemosyne$ python --version
Python 2.7.14
~/software/mnemosyne$ git branch
* master
```

**Comment by pbienst** [comment]
Your system's default python version is still 2.x. Replace python by python3 in the command.

**Comment by iambumblehead** [comment]
Thanks. Humbly, I recommend adding a note in the README. I'm using a fresh ubuntu install and it would appear that Python 2.7.14 is the default here.

**Comment by pbienst** [comment]
Thanks, the doc update should already be in my development tree.

**Comment by iambumblehead** [comment]
I'm looking at this 'snap' guide, which demonstrates an app that is started with this command
```
command: bin/offlineimap
```

Is there a similar command or local binary available for mnemosyne?

**Comment by pbienst** [comment]
Not really. There are bundled installers both for Windows and Linux, though, which don't require any dependencies.
