### ISSUE TITLE
How about saving default database in a way that isn't overwritten on a reinstall?

### ISSUE THREAD

**Issue by subrosa7** [mnemosyne-proj/mnemosyne#45]
I know it's not really a bug, but with Microsoft thinking that everyone needs to "refresh" their computers at every hint of trouble, and them so confidently ensuring us that none of our files will be effected (only programs will need to be reinstalled, you see)...  It's just that I can see other people making the same bonehead mistake I just made.
Bondhead mistake:  After doing a "refresh" I reinstalled Mnemosyne thinking I could just open my card file from wherever I or the program saved it.  Since most programs remember their default save locations, I thought nothing more of it....
Turns out this program is a little different and I'm afraid I just overwrote the default database with a "fresh" one when I reinstalled the program....

Suggestion:  Perhaps along with the default database, the program saves an automatic copy of it somewhere every now and then?  Somewhere like in the MyDocuments folder or something? 

I had months of work stored on those cards and while I'm not complaining, this software is a godsend and nothing is perfect... If by me sharing my experience I could save even one other person from experiencing a devastating loss like this....  You catch my drift...  :)

Thanks,
-Scott

P.S.  If the software already does this?  I am still operating on half a brain cell, and would greatly appreciate a heads up.

**Comment by pbienst** [comment]
Mnemosyne already does this, but in the same directory:

https://mnemosyne-proj.org/help/backups.php

Also see my reply to you in the mailing list.
