### ISSUE TITLE
Periodic popup

### ISSUE THREAD

**Issue by rendaw** [mnemosyne-proj/mnemosyne#54]
This is a kind of out-there request.  I'd like to review for 5 minutes every hour, and have mnemosyne come up automatically and close after the first answered question after 5 minutes are up.

I can set up a systemd job for most of this but command line flags to go directly to review and close after n minutes/x questions would be awesome.

**Comment by pbienst** [comment]
Please submit feature requests here, so that users can vote for it:
https://mnemosyne.uservoice.com/forums/164265-general
