### ISSUE TITLE
Flashcard contents can't be copied from the review view

### ISSUE THREAD

**Issue by marmistrz** [mnemosyne-proj/mnemosyne#56]
Sometimes I want to copy-paste a Chinese character to see the stroke order. If I select the answer for the flashcard, it gets a gray background, but Ctrl+C doesn't copy it to the clipboard, as though as the focus were lost.

**Comment by pbienst** [comment]
This is a side effect of having moved to an upgraded version of the toolkit, and is difficult to address. A workaround is copying from the review widget....
