### ISSUE TITLE
Error during browsing word list

### ISSUE THREAD

**Issue by csimonmoi** [mnemosyne-proj/mnemosyne#57]
![schermata 2018-04-26 alle 11 14 06](https://user-images.githubusercontent.com/16046710/39297137-03c54076-4943-11e8-9fad-75153d3afbfb.png)

**Comment by csimonmoi** [comment]
Hi
My version is 2.6, the latest on your site.
The app remains blocked after error and I have to force it to shut it down.

Ok I can send you my deck. How do I do it?
Thanks

**Comment by pbienst** [comment]
pbienst at gmail dot com

**Comment by csimonmoi** [comment]
As you can see your address gives me an error.

**Comment by pbienst** [comment]
Sorry, try peter dot bienstman at gmail dot com
