### ISSUE TITLE
sometimes typing is backward

### ISSUE THREAD

**Issue by Carl1319** [mnemosyne-proj/mnemosyne#58]
Occasionally, I'll start a new card and the letters, while formed normally, will start appearing (on the front part of the card) from right to left, instead of left to right. They'll still be left-aligned in the box, but, for instance, when I type the word "what" it will appear as "tahw". It's always such a surprise that I haven't been able to track what I have been doing just before this happens. So far, it's always gone back to normal if I close the new card window and then re-open it.

I'm using Mnemosyne 2.6 with PortableApps on Windows 10 pro.

**Comment by pbienst** [comment]
Sorry, the portable apps version is not released by us, and we don't support it....
