### ISSUE TITLE
Not opening: something to do with Open GL 2 libraries not being installed

### ISSUE THREAD

**Issue by tsoapm** [mnemosyne-proj/mnemosyne#60]
![image](https://user-images.githubusercontent.com/40119490/41192165-452dd49a-6bfa-11e8-87bd-4c269523a103.png)

Are these libraries not part of the install package? I just uninstalled Mnemosyne so I could install the latest version, because the Android sync app said I needed to to get it to work, but now it doesn't work at all!

**Comment by pbienst** [comment]
See the instructions on the download page. The first thing to do is making sure your graphics drivers are up to date.

**Comment by tsoapm** [comment]
Not resolved. This isn't even the first time you've simply dismissed something from me. You've probably lost a long-time user, and not just because I feel a bit affronted on a personal level by such a glib and unhelpful response, though I'm sure you put a lot of work into the project and am very surprised that you did reply so quickly, but because I simply can't get the program to open. I installed the latest graphics drivers, which in any case weren't causing me any issues before.  
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.

**Comment by tsoapm** [comment]
Thank you. That did work.

 

The command line options mentioned come after this: "Additionally, if you see a black screen". Since I didn't see a black screen, it didn't seem an appropriate thing to try. I'm not sure what the meaning of this/these argument(s) are, but they don't seem to be documented in the main documentation, just the server and data directory options.

 



Sent: Sunday, June 10, 2018 at 8:23 AM

**Comment by springboard23** [comment]
Glad I was able to point you in the right direction!

**Comment by pbienst** [comment]
Glad I was able to point you in the right direction!
