### ISSUE TITLE
Segfault in Debian "stretch"

### ISSUE THREAD

**Issue by cmealares** [mnemosyne-proj/mnemosyne#62]
Hello, I have just installed Debian "Stretch" and I cannot run mnemosyne.

When I remove .local/share/mnemosyne and .config/mnemosyne 
```
$ mnemosyne
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
QIODevice::write (QProcess): device not open
Erreur de segmentation
```

If I run it again I get :
1) A dialog box with message "Unable to load file, query failed"
2) I close the dialog and another one is raised with "If you are using a USB key, refer to the instructions on the website so as not to be affected by drive letter changes."
3) Then it asks me to select a db file. I select the one it has just created and that brings me back to step 1

Can you suggest a workaround or something to try?

thanks
Christophe - a longtime Mnemosyne user

**Comment by pbienst** [comment]
The errors you get after running it again are probably a consequence of the first error leaving Mnemosyne in a bad state. Deleting/moving .config/Mnemosyne (or the directory which contains config.db) should address this.

As for the first error, I suspect the Debian update has messed up the Qt libraries. Perhaps there are different incompatible versions installed? In any case, this is probably not really a Mnemosyne error and it's better to look for Debian specific help, like e.g. contacting the person that made a Debian package https://github.com/mnemosyne-proj/mnemosyne/issues/37

**Comment by cmealares** [comment]
My computer is brand new and I have just installed Debian Stretch. I have only one Mnemosyne version that I have installed with the package manager (aptitude).

I actually got the second error first... 
I wanted to retrieve my Mnemosyne data from my previous computer. To do that, I copied .local/share/mnemosyne and .config/mnemosyne from this old computer to the new one.

Then I launched Mnemosyne but it would not start. So I thought that I should try without my old database. That is why I deleted these 2 directories. But it does not solve the issue.

I have also tried in another user account and I got the same problem.

**Comment by pbienst** [comment]
Try first to copy only .local/share/mnemosyne and delete .config/mnemosyne. If the name of your database is the recommended 'default.db', it should pick that up immediately. Otherwise, just do 'File-open' and select your database.

**Comment by cmealares** [comment]
```
$ /bin/rm -rf .config/mnemosyne
$ mnemosyne 
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
```
And then, the error dialog comes up with "Unable to load file, query failed"
After I close the dialog boxes, a file selection dialog comes up and shows the content of .local/share/mnemosyne.
Whenever I select default.db the message "Unable to load file, query failed" comes up again.

**Comment by pbienst** [comment]
Perhaps default.db is corrupt? Can you share the file?

**Comment by cmealares** [comment]
Please find attached the db that Mnemosyne creates when I do not try to recover my old db.

[default.db.zip](https://github.com/mnemosyne-proj/mnemosyne/files/2100980/default.db.zip)

**Comment by pbienst** [comment]
I'm afraid that database is completely corrupted: it does not seem to contain any cards anymore...

**Comment by cmealares** [comment]
This is the database that Mnemosyne has just created (it's not my backup). 
I expect it to be empty but Mnemosyne cannot open it.

**Comment by pbienst** [comment]
It seems the database was not properly finalised then, as it misses some version information which should be created when you save the database. 

You mentioned a segfault, which could certainly explain this if you get this segfault every time.

Does opening your real database work?

Have you tried upgrading/downgrading the PyQt libraries?

**Comment by cmealares** [comment]
Please fin attached my real database.
I cannot open it. See below:
```
$ /bin/rm -rf .local/share/mnemosyne  .config/mnemosyne
$ cp -R cmealareBAK/.local/share/mnemosyne   .local/share
$ mnemosyne 
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
QIODevice::write (QProcess): device not open
Erreur de segmentation
```
The messages I get in the dialog boxes are :
- You appear to have missed some reviews. Don't worry too much about this backlog...
- Archiving old logs...
[default.db.zip](https://github.com/mnemosyne-proj/mnemosyne/files/2103731/default.db.zip)

**Comment by cmealares** [comment]
I've made some queries in the Debian Bug Tracking System and found this one:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=883333

I have installed the packages they recommend and I can go a bit further. So you are right, the Debian package is broken. I might end up logging a bug into their BTS.

**Comment by pbienst** [comment]
Ok, good to know!
