### ISSUE TITLE
Unable to close the small progress bar windows

### ISSUE THREAD

**Issue by woohgit** [mnemosyne-proj/mnemosyne#63]
After sync with android or clicking on the `Show statistics` button and clicking through the tabs, most of the time the popup progress bar gtk windows will remain and can't be closed.

Some cases closing the statistics window closes the inactive windows, but after the sync they remain there and can't be closed. (3 or 4 windows)

<img src="https://wooh.hu/mnemosyne.png" style="width: 300px;"/>

**Comment by woohgit** [comment]
@pbienst Cool. Can we expect a stable release soon?

**Comment by pbienst** [comment]
I hope to have a public test realise end July.
