### ISSUE TITLE
mnemosyne claims that used media files are unused and wants to delete them

### ISSUE THREAD

**Issue by matkoniecz** [mnemosyne-proj/mnemosyne#70]
Mnemosyne 2.2.1.3 available as package in Ubuntu 16.04 wants to delete for example files with ' character in name as unused, even if these files are used on using File | Compact option.

I tried to reproduce it in recent version but failed due to #69

**Comment by pbienst** [comment]
Please create a new bug report after you manage to update to the latest version and confirm if the issue is still there. 2.2 is really ancient....
