### ISSUE TITLE
pyqt download links to pyqt4 download

### ISSUE THREAD

**Issue by matkoniecz** [mnemosyne-proj/mnemosyne#72]
https://github.com/mnemosyne-proj/mnemosyne#runtime-requirements has "PyQt 5.6 or later" linking to https://riverbankcomputing.com/software/pyqt/download instead of https://www.riverbankcomputing.com/software/pyqt/download5

**Comment by matkoniecz** [comment]
Can you confirm that https://www.riverbankcomputing.com/software/pyqt/download5 is preferable to https://www.riverbankcomputing.com/software/pyqt/download ?

I can make it as the next PR, after #75

**Comment by pbienst** [comment]
I've edited that file myself with your changes. I will push out a revision soon.
