### ISSUE TITLE
The repository contains binary .so files (probably build artifacts)

### ISSUE THREAD

**Issue by marmistrz** [mnemosyne-proj/mnemosyne#85]
In `mnemosyne/mnemosyne/android/app/src/main/libs/armeabi-v7a/`

They should not be the part of repository. 

cc #83

**Comment by pbienst** [comment]
The reason they are added to the repository is so that somebody who wants to start working on the Android client doesn't have to deal with the all the crystax stuff if they don't want to...

**Comment by marmistrz** [comment]
And what are binaries in https://github.com/mnemosyne-proj/mnemosyne/tree/c2d0aa4a69021907188863a65ff96bed5874a5d2/mnemosyne/android/app/src/main/assets/python

**Comment by pbienst** [comment]
These are the required support libraries from crystax, built from the crystax sources (although I just copied them from their binary package).
