### ISSUE TITLE
latex in macOS

### ISSUE THREAD

**Issue by atophys** [mnemosyne-proj/mnemosyne#88]
I installed MiKTeX in order to view latex content in flashcards but I also had to make two other changes to finally make it work:
1-. In the .../Library/Mnemosyne/config.py file I changed the path for the latex and dvipng variables to /usr/local/bin/latex (and dvipng), which was the path where MikTeX installed the packages.
2-. In this same file, the latex command supposedly uses -interactiononstopmode option, but the right option is: -interaction=nonstopmode

**Comment by pbienst** [comment]
Thanks for the info, I forwarded this to our OSX packager, Devin.

**Comment by devvmh** [comment]
i don't even see a config.py file in the default install, did you have to create this file?

Are you able to make a pull request that adds this to the macos build process? I'm also happy to help make this pull request, but i would need your help since I don't know how the LaTeX support works

**Comment by pbienst** [comment]
Hi atophys, could you please provide the info Devin requested? Thanks!

**Comment by atophys** [comment]
Of course. I am sorry for the big delay in my answer but I was moving to another country to live and stuff like that. But now to the point:

The only two lines that I changed were the following:

# Latex command.
#latex = "/Library/TeX/texbin/latex -output-format=dvi -interactiononstopmode"
latex = "/usr/local/bin/latex -output-format=dvi -interaction=nonstopmode"

# Latex dvipng command.
#dvipng = "/Library/TeX/texbin/dvipng -D 200 -T tight tmp.dvi"
dvipng = "/usr/local/bin/dvipng -D 200 -T tight tmp.dvi"

I hope this helps.

**Comment by pbienst** [comment]
Devin, how should we proceed here? Thanks!

**Comment by devvmh** [comment]
I will look into this soon (next two weeks) and post a pull request
