### ISSUE TITLE
Spaces are stripped in main window

### ISSUE THREAD

**Issue by dbedrenko** [mnemosyne-proj/mnemosyne#89]
When I write a question that contains some ASCII art, like:

```
Left rotate on '7':

       7
     /
   5
     \
       6
```

And I have "Left" alignment selected in the settings, it strips out all the spaces when shown in the main window:

```
Left rotate on '7':

7
/
5
\
6
```

When I go to edit the card, the spaces are still there. I tried to prepend the each line with a placeholder character `.` before the spaces, but it still stripped out the spaces.

Just because the alginment is set to left, doesn't mean that it should strip out the spaces.

PS: Love the app! Already made 150 cards!

**Comment by pbienst** [comment]
This is an html issue and not really a Mnemosyne issue.
I've been doing some googling, and it seems you need to wrap your text in <pre></pre> tags: https://css-tricks.com/almanac/properties/w/whitespace/

**Comment by dbedrenko** [comment]
That's a workaround I guess, but it changes the font, makes it monospace and removes wrapping (so that I have to scroll horizontally with the mouse). Didn't realise the cards are HTML

Thanks anyway

**Comment by pbienst** [comment]
Yes, the widget to display the cards is a little html browser, with all the advantages and disadvantages that this entails...
Other option is using 'real' images as opposed to ascii art.
